name: Deploy
on: push

jobs:
    deploy:
        runs-on: ubuntu-latest

        # Ejemplo de servicio Redis
        services:
            redis:
                image: redis
                ports:
                    - 6379

        steps:
            - name: Install Redis tools
              run: sudo apt install redis-tools -y
            - name: Test redis
              run: redis-cli ping
            - name: Display repo variables
              run: |
                echo "NAME: ${{ vars.NAME }}"
            - name: Setup
              uses: actions/setup-node@v4
              with:
                node-version: 18