name: Deploy
on: push

jobs:
    deploy:
        runs-on: ubuntu-latest

        # Ejemplo de servicio Redis
        # Esto descarga la imagen de docker para poder utilizar dentro del job
        services:
            redis:
                image: redis
                ports:
                    - 6379

        steps:
            - name: Install Redis tools
              run: sudo apt-get update -y && sudo apt-get install redis-tools -y
            - name: Test redis
              run: redis-cli -h localhost -p 6379 ping
            - name: Display repo variables
              run: |
                echo "NAME: ${{ vars.NAME }}"
            - name: Setup
              uses: actions/setup-node@v4
              with:
                node-version: 18