name: Deploy
on: push

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Display repo variables
              run: |
                echo "NAME: ${{ vars.NAME }}"
            - name: Setup
              uses: actions/setup-node@v4
              with:
                node-version: 18